---
- name: Set Password Policy
  hosts: "{{ host }}"
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Set Password Maximum Age
      lineinfile:
        dest: /etc/login.defs
        regexp: '^#?PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS 60'

    - name: Set Password Minimum Age
      lineinfile:
        dest: /etc/login.defs
        regexp: '^#?PASS_MIN_DAYS'
        line: 'PASS_MIN_DAYS 5'

    - name: Set Password Warning Age
      lineinfile:
        dest: /etc/login.defs
        regexp: '^#?PASS_WARN_AGE'
        line: 'PASS_WARN_AGE 14'

    - name: Set Password Length
      lineinfile:
        dest: /etc/login.defs
        regexp: '^#?PASS_MIN_LEN'
        line: 'PASS_MIN_LEN 14'
