---
- name: Ensure PAM settings for password complexity
  hosts: "{{ host }}"
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Ensure PAM minlen is set
      lineinfile:
        dest: /etc/security/pwquality.conf
        regexp: '^#?\s*minlen'
        line: 'minlen=8'

    - name: Ensure PAM ucredit is set
      lineinfile:
        dest: /etc/security/pwquality.conf
        regexp: '^#?\s*ucredit'
        line: 'ucredit=-1'

    - name: Ensure PAM ocredit is set
      lineinfile:
        dest: /etc/security/pwquality.conf
        regexp: '^#?\s*ocredit'
        line: 'ocredit=-1'

    - name: Ensure PAM dcredit is set
      lineinfile:
        dest: /etc/security/pwquality.conf
        regexp: '^#?\s*dcredit'
        line: 'dcredit=-1'

    - name: Ensure PAM lcredit is set
      lineinfile:
        dest: /etc/security/pwquality.conf
        regexp: '^#?\s*lcredit'
        line: 'lcredit=-1'
