---
- name: Ensure default target is multi-user
  hosts: "{{ host }}"
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Verify default target is multi-user
      shell: ls -l /etc/systemd/system/default.target | grep multi-user
      register: multi
      ignore_errors: true

    - name: Change default target to multi-user
      file:
        src: /usr/lib/systemd/system/multi-user.target
        dest: /etc/systemd/system/default.target
        state: link
      when: "multi.rc == 1"
