---
- name: Deduplicate SSH configuration values and set appropriate settings
  hosts: "{{ host }}"
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Deduplicate PermitRootLogin in /etc/ssh/sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        create: false
        regexp: '(?i)\s*PermitRootLogin\s+'
        state: absent

    - name: Insert correct PermitRootLogin line to /etc/ssh/sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        create: true
        line: 'PermitRootLogin no'
        state: present
        insertbefore: '^[#\s]*Match'
        validate: '/usr/sbin/sshd -t -f %s'
